Update to Freertos 10.3.1 Add CortexM33 support
stm32duino/STM32FreeRTOS pull request #48
Opened 2022-02-17 16:04 UTC by ABOSTM

* Update to Freertos 10.3.1
* Add CortexM33 support 
### STM32FreeRTOS v10.3.1
| Board | AnalogRead_DigitalRead | frBlinkPrint | frLiuLayland | frBlink (CMSIS-RTOSv2) | Blinky (CMSIS-RTOSv2) |
| --- | :---: | :---: | :---: | :---: | :---: |
| [Nucleo F091RC (Cortex-M0)](http://www.st.com/en/evaluation-tools/nucleo-f091rc.html) | PASSED | PASSED | FAILED | PASSED | PASSED |
| [Nucleo G071RB (Cortex-M0+)](http://www.st.com/en/evaluation-tools/nucleo-g071rb.html) | PASSED | PASSED | FAILED | PASSED | PASSED |
| [Nucleo F103RB (Cortex-M3)](http://www.st.com/en/evaluation-tools/nucleo-f103rb.html) | PASSED | PASSED | PASSED | PASSED | PASSED |
| [Nucleo L476RG (Cortex-M4)](http://www.st.com/en/evaluation-tools/nucleo-l476rg.html) | PASSED | PASSED | PASSED | PASSED | PASSED |
| [Nucleo H743ZI (Cortex-M7)](https://www.st.com/en/evaluation-tools/nucleo-h743zi.html) | PASSED | PASSED | PASSED | PASSED | PASSED |
| [Nucleo L552ZE-Q (Cortex-M33)](https://www.st.com/en/evaluation-tools/nucleo-l552ze-q.html) | PASSED | PASSED | PASSED | PASSED | PASSED |
| [Nucleo U575ZI-Q (Cortex-M33)](https://www.st.com/en/evaluation-tools/nucleo-u575zi-q.html) | PASSED | PASSED | PASSED | PASSED | PASSED |

2022-02-21 11:23 UTC, ABOSTM commented
*Edit*
Fix frLiuLayland test on CM0 and CM0+

2022-02-22 15:08 UTC, fpistm requested changes

2022-02-22 15:08 UTC, fpistm commented on examples/frLiuLayland/frLiuLayland.ino
>    Serial.println("Period,CPU,Priority");
```suggestion
  Serial.println(micros() - t);
  Serial.println("Starting tasks - period and CPU in ticks");
  Serial.println("Period,CPU,Priority");
  Serial.flush();
```

2022-02-23 10:34 UTC, ABOSTM commented on examples/frLiuLayland/frLiuLayland.ino
>    Serial.println("Period,CPU,Priority");
Done. + one more flush

2022-02-23 10:44 UTC, fpistm approved these changes

2022-02-23 13:20 UTC, merged